modLoader = "javafml"
loaderVersion = "[21,)"
issueTrackerURL = "https://github.com/QWERTY770/SweetPotatoReborn/issues"
license = "Apache-2.0"

[[mods]]
modId = "spmreborn"
version = "${version}"
displayName = "Sweet Potato Reborn"
displayURL="https://github.com/QWERTY770/SweetPotatoReborn"
authors = "QWERTY770"
description = '''
Try new kinds of food, crops & magic in Sweet Potato Mod!
'''
logoFile = "icon.png"

[[mixins]]
config1="spmreborn-common.mixins.json"
config2="spmreborn.mixins.json"

[[dependencies.spmreborn]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spmreborn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spmreborn]]
modId = "architectury"
mandatory = true
versionRange = "[13.0,)"
ordering = "NONE"
side = "BOTH"