modLoader = "javafml"
loaderVersion = "[2,)"
license = "Apache-2.0"
issueTrackerURL = "https://github.com/QWERTY770/SweetPotatoReborn/issues"

[[mods]]
modId = "spmreborn"
version = "${version}"
displayName = "Sweet Potato Reborn"
displayURL="https://github.com/QWERTY770/SweetPotatoReborn"
authors = "QWERTY770"
description = '''
Try new kinds of food, crops & magic in Sweet Potato Mod!
'''
logoFile = "icon.png"

[[mixins]]
config="spmreborn-common.mixins.json"
config2="spmreborn.mixins.json"

[[dependencies.spmreborn]]
modId = "neoforge"
type = "required"
versionRange = "[21.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spmreborn]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spmreborn]]
modId = "architectury"
type = "required"
versionRange = "[14.0,)"
ordering = "NONE"
side = "BOTH"