//file:noinspection GroovyAssignabilityCheck
plugins {
    id "architectury-plugin" version "3.4-SNAPSHOT"
    id "dev.architectury.loom" version "1.7-SNAPSHOT" apply false
    id "com.modrinth.minotaur" version "2.+" apply false
    id 'maven-publish'
}

architectury {
    minecraft = rootProject.minecraft_version
}

subprojects {
    repositories {
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }
        maven { url 'https://mirrors.jcut.edu.cn/bmclapi/' }
        maven { url 'https://mirrors.lzu.edu.cn/bmclapi' }
        maven { url 'https://lss233.littleservice.cn/repositories/minecraft/' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
    }
    apply plugin: "dev.architectury.loom"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    base {
        archivesName = rootProject.archives_base_name + "-" + project.name
    }
    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        // The following line declares the mojmap mappings, you may use other mappings as well
        mappings loom.layered {
            officialMojangMappings()
            parchment("org.parchmentmc.data:parchment-1.21.4:${rootProject.parchment_version}")
        }
        implementation 'com.google.code.findbugs:jsr305:3.0.2'
        implementation 'com.google.errorprone:error_prone_annotations:2.18.0'
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = "UTF-8"
        it.options.release = 21
    }

    java {
        withSourcesJar()
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
}

allprojects {
    archives_base_name = rootProject.archives_base_name
    version = rootProject.mod_version
}

subprojects {
    if (System.getenv("MR_TOKEN")) {
        apply plugin: 'com.modrinth.minotaur'
        def modLoaders = project.mr_loader.toString().split(",") as List
        modrinth {
            token.set System.getenv("MR_TOKEN")
            projectId.set "42Oytc0x"
            versionNumber.set "${project.version}-${modLoaders[0]}"
            versionName.set String.format(
                    /*format=*/ rootProject.mr_version_name_format.toString(),
                    rootProject.mr_version_game_range,
                    project.mr_loader_display,
                    rootProject.mr_version_mod_abbr,
                    rootProject.mr_version_display
            )
            changelog.set rootProject.mr_version_changelog
            versionType.set rootProject.mr_version_type
            gameVersions = rootProject.mr_version_game.toString().split(",") as List
            loaders.set modLoaders
            detectLoaders.set false
            autoAddDependsOn.set false

            dependencies {
                required.project 'architectury-api'
                if (modLoaders.contains("fabric")) {
                    required.project 'fabric-api'
                }
            }

            uploadFile.set tasks.remapJar
            additionalFiles = [tasks.remapSourcesJar]

            debugMode = System.getenv("MR_DEBUG_MODE") == '1'
        }
    }
}